#pragma once
// Auto-generated by tools/generate_localization_bindings.ps1. Do not edit by hand.
#include <string>

struct LocalizationKeysAccessor
{
        const char* Get(const std::string& key) const;

        // Toggle me with %s
        inline const char* Toggle_me_with_s() const { return Get("Toggle me with %s"); }

        // Toggle Online with %s
        inline const char* Toggle_Online_with_s() const { return Get("Toggle Online with %s"); }

        // Toggle HUD with %s
        inline const char* Toggle_HUD_with_s() const { return Get("Toggle HUD with %s"); }

        // Generate Debug Logs
        inline const char* Generate_Debug_Logs() const { return Get("Generate Debug Logs"); }

        // Debug_log_details
        inline const char* Debug_log_details() const { return Get("Debug_log_details"); }

        // Online
        inline const char* Online() const { return Get("Online"); }

        // Gameplay settings
        inline const char* Gameplay_settings() const { return Get("Gameplay settings"); }

        // Custom palettes
        inline const char* Custom_palettes() const { return Get("Custom palettes"); }

        // Hitbox overlay
        inline const char* Hitbox_overlay() const { return Get("Hitbox overlay"); }

        // FrameHistory
        inline const char* FrameHistory() const { return Get("FrameHistory"); }

        // Framedata
        inline const char* Framedata() const { return Get("Framedata"); }

        // Avatar settings
        inline const char* Avatar_settings() const { return Get("Avatar settings"); }

        // Controller Settings
        inline const char* Controller_Settings() const { return Get("Controller Settings"); }

        // Local Controller Override
        inline const char* Local_Controller_Override() const { return Get("Local Controller Override"); }

        // Controller_override_help
        inline const char* Controller_override_help() const { return Get("Controller_override_help"); }

        // Refresh controllers
        inline const char* Refresh_controllers() const { return Get("Refresh controllers"); }

        // Controller_refresh_help
        inline const char* Controller_refresh_help() const { return Get("Controller_refresh_help"); }

        // Open Joy.cpl
        inline const char* Open_Joy_cpl() const { return Get("Open Joy.cpl"); }

        // Auto-refresh
        inline const char* Auto_refresh() const { return Get("Auto-refresh"); }

        // Auto_refresh_warning
        inline const char* Auto_refresh_warning() const { return Get("Auto_refresh_warning"); }

        // No input devices detected.
        inline const char* No_input_devices_detected() const { return Get("No input devices detected."); }

        // STEAM INPUT: %s
        inline const char* STEAM_INPUT_s() const { return Get("STEAM INPUT: %s"); }

        // ON
        inline const char* ON() const { return Get("ON"); }

        // OFF
        inline const char* OFF() const { return Get("OFF"); }

        // Steam_input_active_notice
        inline const char* Steam_input_active_notice() const { return Get("Steam_input_active_notice"); }

        // Steam_input_limitations
        inline const char* Steam_input_limitations() const { return Get("Steam_input_limitations"); }

        // Swap P1 Controller to P2
        inline const char* Swap_P1_Controller_to_P2() const { return Get("Swap P1 Controller to P2"); }

        // Controller_swap_hint
        inline const char* Controller_swap_hint() const { return Get("Controller_swap_hint"); }

        // Multiple keyboards override
        inline const char* Multiple_keyboards_override() const { return Get("Multiple keyboards override"); }

        // Keyboard_player1_help
        inline const char* Keyboard_player1_help() const { return Get("Keyboard_player1_help"); }

        // No keyboards selected
        inline const char* No_keyboards_selected() const { return Get("No keyboards selected"); }

        // No keyboards detected.
        inline const char* No_keyboards_detected() const { return Get("No keyboards detected."); }

        // P1 Keyboards
        inline const char* P1_Keyboards() const { return Get("P1 Keyboards"); }

        // Map
        inline const char* Map() const { return Get("Map"); }

        // Rename
        inline const char* Rename() const { return Get("Rename"); }

        // Ignore
        inline const char* Ignore() const { return Get("Ignore"); }

        // Rename keyboard
        inline const char* Rename_keyboard() const { return Get("Rename keyboard"); }

        // Set a custom name for this keyboard.
        inline const char* Set_a_custom_name_for_this_keyboard() const { return Get("Set a custom name for this keyboard."); }

        // Save
        inline const char* Save() const { return Get("Save"); }

        // Cancel
        inline const char* Cancel() const { return Get("Cancel"); }

        // Clear
        inline const char* Clear() const { return Get("Clear"); }

        // Configure keyboard mapping
        inline const char* Configure_keyboard_mapping() const { return Get("Configure keyboard mapping"); }

        // Unbound
        inline const char* Unbound() const { return Get("Unbound"); }

        // Press a key...
        inline const char* Press_a_key() const { return Get("Press a key..."); }

        // Select game mode:
        inline const char* Select_game_mode() const { return Get("Select game mode:"); }

        // Stage
        inline const char* Stage() const { return Get("Stage"); }

        // Player 1
        inline const char* Player_1() const { return Get("Player 1"); }

        // Gap:
        inline const char* Gap() const { return Get("Gap:"); }

        // Advantage:
        inline const char* Advantage() const { return Get("Advantage:"); }

        // Player 2
        inline const char* Player_2() const { return Get("Player 2"); }

        // Player 1:
        inline const char* Player_1_2() const { return Get("Player 1:"); }

        // Player 2:
        inline const char* Player_2_2() const { return Get("Player 2:"); }

        // Copy to clipboard
        inline const char* Copy_to_clipboard() const { return Get("Copy to clipboard"); }

        // Search
        inline const char* Search() const { return Get("Search"); }

        // System_log_copied
        inline const char* System_log_copied() const { return Get("System_log_copied"); }

        // Reload custom palettes
        inline const char* Reload_custom_palettes() const { return Get("Reload custom palettes"); }

        // Select character
        inline const char* Select_character() const { return Get("Select character"); }

        // Select palette
        inline const char* Select_palette() const { return Get("Select palette"); }

        // Select file
        inline const char* Select_file() const { return Get("Select file"); }

        // Gradient generator
        inline const char* Gradient_generator() const { return Get("Gradient generator"); }

        // Undo
        inline const char* Undo() const { return Get("Undo"); }

        // Redo
        inline const char* Redo() const { return Get("Redo"); }

        // Cannot save with Highlight mode on!
        inline const char* Cannot_save_with_Highlight_mode_on() const { return Get("Cannot save with Highlight mode on!"); }

        // Save with bloom effect
        inline const char* Save_with_bloom_effect() const { return Get("Save with bloom effect"); }

        // Bloom effects cannot be changed until a new round is started
        inline const char* Bloom_effects_cannot_be_changed_until_a_new_round_is_started() const { return Get("Bloom effects cannot be changed until a new round is started"); }

        // Palette name:
        inline const char* Palette_name() const { return Get("Palette name:"); }

        // Creator (optional):
        inline const char* Creator_optional() const { return Get("Creator (optional):"); }

        // Palette description (optional):
        inline const char* Palette_description_optional() const { return Get("Palette description (optional):"); }

        // Save palette
        inline const char* Save_palette() const { return Get("Save palette"); }

        // Error, no filename given
        inline const char* Error_no_filename_given() const { return Get("Error, no filename given"); }

        // Error, not a valid filename
        inline const char* Error_not_a_valid_filename() const { return Get("Error, not a valid filename"); }

        // '%s' saved successfully
        inline const char* s_saved_successfully() const { return Get("'%s' saved successfully"); }

        // '%s' save failed
        inline const char* s_save_failed() const { return Get("'%s' save failed"); }

        // Overwrite_confirmation_prompt
        inline const char* Overwrite_confirmation_prompt() const { return Get("Overwrite_confirmation_prompt"); }

        // OK
        inline const char* OK() const { return Get("OK"); }

        // Reset palette
        inline const char* Reset_palette() const { return Get("Reset palette"); }

        // Out of bounds
        inline const char* Out_of_bounds() const { return Get("Out of bounds"); }

        // ONLINE PALETTE
        inline const char* ONLINE_PALETTE() const { return Get("ONLINE PALETTE"); }

        // Creator: %s
        inline const char* Creator_s() const { return Get("Creator: %s"); }

        // Description: %s
        inline const char* Description_s() const { return Get("Description: %s"); }

        // Has bloom effect
        inline const char* Has_bloom_effect() const { return Get("Has bloom effect"); }

        // Random selection
        inline const char* Random_selection() const { return Get("Random selection"); }

        // Start index
        inline const char* Start_index() const { return Get("Start index"); }

        // End index
        inline const char* End_index() const { return Get("End index"); }

        // Start color
        inline const char* Start_color() const { return Get("Start color"); }

        // End color
        inline const char* End_color() const { return Get("End color"); }

        // Swap colors
        inline const char* Swap_colors() const { return Get("Swap colors"); }

        // Generate gradient
        inline const char* Generate_gradient() const { return Get("Generate gradient"); }

        // Refresh
        inline const char* Refresh() const { return Get("Refresh"); }

        // Recording side: %c
        inline const char* Recording_side_c() const { return Get("Recording side: %c"); }

        // Switch recording side
        inline const char* Switch_recording_side() const { return Get("Switch recording side"); }

        // Add/Remove
        inline const char* Add_Remove() const { return Get("Add/Remove"); }

        // Frame
        inline const char* Frame() const { return Get("Frame"); }

        // Literal
        inline const char* Literal() const { return Get("Literal"); }

        // Command
        inline const char* Command() const { return Get("Command"); }

        // Edit Input
        inline const char* Edit_Input() const { return Get("Edit Input"); }

        // Direction
        inline const char* Direction() const { return Get("Direction"); }

        // Bind
        inline const char* Bind() const { return Get("Bind"); }

        // Menu action
        inline const char* Menu_action() const { return Get("Menu action"); }

        // Battle action
        inline const char* Battle_action() const { return Get("Battle action"); }

        // Close
        inline const char* Close() const { return Get("Close"); }

        // Set all to default
        inline const char* Set_all_to_default() const { return Get("Set all to default"); }

        // Ignored keyboards
        inline const char* Ignored_keyboards() const { return Get("Ignored keyboards"); }

        // No ignored keyboards.
        inline const char* No_ignored_keyboards() const { return Get("No ignored keyboards."); }

        // Unignore
        inline const char* Unignore() const { return Get("Unignore"); }

        // (connected)
        inline const char* connected() const { return Get("(connected)"); }

        // (not connected)
        inline const char* not_connected() const { return Get("(not connected)"); }

        // Mapping for %s
        inline const char* Mapping_for_s() const { return Get("Mapping for %s"); }

        // Test
        inline const char* Test() const { return Get("Test"); }

        // Player 1 Controller
        inline const char* Player_1_Controller() const { return Get("Player 1 Controller"); }

        // Player 2 Controller
        inline const char* Player_2_Controller() const { return Get("Player 2 Controller"); }

        // Loaded settings.ini values
        inline const char* Loaded_settings_ini_values() const { return Get("Loaded settings.ini values"); }

        // Current online players:
        inline const char* Current_online_players() const { return Get("Current online players:"); }

        // <No data>
        inline const char* No_data() const { return Get("<No data>"); }

        // Avatar
        inline const char* Avatar() const { return Get("Avatar"); }

        // Color
        inline const char* Color() const { return Get("Color"); }

        // Accessory 1
        inline const char* Accessory_1() const { return Get("Accessory 1"); }

        // Accessory 2
        inline const char* Accessory_2() const { return Get("Accessory 2"); }

        // CONNECT TO NETWORK MODE FIRST
        inline const char* CONNECT_TO_NETWORK_MODE_FIRST() const { return Get("CONNECT TO NETWORK MODE FIRST"); }

        // FrameHistory help
        inline const char* FrameHistory_help() const { return Get("FrameHistory help"); }

        // FrameHistory auto reset help
        inline const char* FrameHistory_auto_reset_help() const { return Get("FrameHistory auto reset help"); }

        // Box width
        inline const char* Box_width() const { return Get("Box width"); }

        // Box height
        inline const char* Box_height() const { return Get("Box height"); }

        // spacing
        inline const char* spacing() const { return Get("spacing"); }

        // Enable##framehistory_section
        inline const char* Enable_framehistory_section() const { return Get("Enable##framehistory_section"); }

        // Auto Reset##Reset after each idle frame
        inline const char* Auto_Reset_Reset_after_each_idle_frame() const { return Get("Auto Reset##Reset after each idle frame"); }

        // Enable##framedata_section
        inline const char* Enable_framedata_section() const { return Get("Enable##framedata_section"); }

        // Advantage on stagger hit
        inline const char* Advantage_on_stagger_hit() const { return Get("Advantage on stagger hit"); }

        // YOU ARE NOT IN MATCH!
        inline const char* YOU_ARE_NOT_IN_MATCH() const { return Get("YOU ARE NOT IN MATCH!"); }

        // YOU ARE NOT IN TRAINING MODE OR REPLAY THEATER!
        inline const char* YOU_ARE_NOT_IN_TRAINING_MODE_OR_REPLAY_THEATER() const { return Get("YOU ARE NOT IN TRAINING MODE OR REPLAY THEATER!"); }

        // YOU ARE NOT IN A MATCH, IN TRAINING MODE OR REPLAY THEATER!
        inline const char* YOU_ARE_NOT_IN_A_MATCH_IN_TRAINING_MODE_OR_REPLAY_THEATER() const { return Get("YOU ARE NOT IN A MATCH, IN TRAINING MODE OR REPLAY THEATER!"); }

        // THERE WAS AN ERROR LOADING ONE/BOTH OF THE CHARACTERS
        inline const char* THERE_WAS_AN_ERROR_LOADING_ONE_BOTH_OF_THE_CHARACTERS() const { return Get("THERE WAS AN ERROR LOADING ONE/BOTH OF THE CHARACTERS"); }

        // Palette editor
        inline const char* Palette_editor() const { return Get("Palette editor"); }

        // YOU ARE NOT IN MATCH! (Replay)
        inline const char* YOU_ARE_NOT_IN_MATCH_Replay() const { return Get("YOU ARE NOT IN MATCH! (Replay)"); }

        // YOU ARE NOT IN REPLAY MENU!
        inline const char* YOU_ARE_NOT_IN_REPLAY_MENU() const { return Get("YOU ARE NOT IN REPLAY MENU!"); }

        // YOU ARE NOT IN CHARACTER SELECTION!
        inline const char* YOU_ARE_NOT_IN_CHARACTER_SELECTION() const { return Get("YOU ARE NOT IN CHARACTER SELECTION!"); }

        // Hide HUD
        inline const char* Hide_HUD() const { return Get("Hide HUD"); }

        // Toggle Rewind
        inline const char* Toggle_Rewind() const { return Get("Toggle Rewind"); }

        // Replay Database
        inline const char* Replay_Database() const { return Get("Replay Database"); }

        // Enable/Disable Automatic Replay Uploads?
        inline const char* Enable_Disable_Automatic_Replay_Uploads() const { return Get("Enable/Disable Automatic Replay Uploads?"); }

        // Main window notification format
        inline const char* Main_window_notification_format() const { return Get("Main window notification format"); }

        // Replay_uploads_description
        inline const char* Replay_uploads_description() const { return Get("Replay_uploads_description"); }

        // Enable/Disable Upload
        inline const char* Enable_Disable_Upload() const { return Get("Enable/Disable Upload"); }

        // Discord
        inline const char* Discord() const { return Get("Discord"); }

        // Forum
        inline const char* Forum() const { return Get("Forum"); }

        // GitHub
        inline const char* GitHub() const { return Get("GitHub"); }

        // Player1
        inline const char* Player1() const { return Get("Player1"); }

        // Player2
        inline const char* Player2() const { return Get("Player2"); }

        // Draw hitbox/hurtbox
        inline const char* Draw_hitbox_hurtbox() const { return Get("Draw hitbox/hurtbox"); }

        // Draw origin
        inline const char* Draw_origin() const { return Get("Draw origin"); }

        // Draw collision
        inline const char* Draw_collision() const { return Get("Draw collision"); }

        // Draw throw/range boxes
        inline const char* Draw_throw_range_boxes() const { return Get("Draw throw/range boxes"); }

        // Origin_point_note
        inline const char* Origin_point_note() const { return Get("Origin_point_note"); }

        // Collision_box_note
        inline const char* Collision_box_note() const { return Get("Collision_box_note"); }

        // Throw range help
        inline const char* Throw_range_help() const { return Get("Throw range help"); }

        // Freeze frame:
        inline const char* Freeze_frame() const { return Get("Freeze frame:"); }

        // Frame Count
        inline const char* Frame_Count() const { return Get("Frame Count"); }

        // Reset
        inline const char* Reset() const { return Get("Reset"); }

        // Freeze animation
        inline const char* Freeze_animation() const { return Get("Freeze animation"); }

        // Stop timer
        inline const char* Stop_timer() const { return Get("Stop timer"); }

        // Step frames
        inline const char* Step_frames() const { return Get("Step frames"); }

        // YOU ARE NOT IN TRAINING, VERSUS, OR REPLAY!
        inline const char* YOU_ARE_NOT_IN_TRAINING_VERSUS_OR_REPLAY() const { return Get("YOU ARE NOT IN TRAINING, VERSUS, OR REPLAY!"); }

        // Game Mode
        inline const char* Game_Mode() const { return Get("Game Mode"); }

        // Enable##hitbox_overlay_section
        inline const char* Enable_hitbox_overlay_section() const { return Get("Enable##hitbox_overlay_section"); }

        // Custom palette reload
        inline const char* Custom_palette_reload() const { return Get("Custom palette reload"); }

        // Enable##framehistory_section checkbox
        inline const char* Enable_framehistory_section_checkbox() const { return Get("Enable##framehistory_section checkbox"); }

        // Draw hitbox/hurtbox##hitbox_overlay_section
        inline const char* Draw_hitbox_hurtbox_hitbox_overlay_section() const { return Get("Draw hitbox/hurtbox##hitbox_overlay_section"); }

        // Draw origin##hitbox_overlay_section
        inline const char* Draw_origin_hitbox_overlay_section() const { return Get("Draw origin##hitbox_overlay_section"); }

        // Draw collision##hitbox_overlay_section
        inline const char* Draw_collision_hitbox_overlay_section() const { return Get("Draw collision##hitbox_overlay_section"); }

        // Step frames##hitbox_overlay_section
        inline const char* Step_frames_hitbox_overlay_section() const { return Get("Step frames##hitbox_overlay_section"); }

        // Gameplay settings header
        inline const char* Gameplay_settings_header() const { return Get("Gameplay settings header"); }

        // Hide HUD checkbox
        inline const char* Hide_HUD_checkbox() const { return Get("Hide HUD checkbox"); }

        // States
        inline const char* States() const { return Get("States"); }

        // Log
        inline const char* Log() const { return Get("Log"); }

        // Replay Rewind
        inline const char* Replay_Rewind() const { return Get("Replay Rewind"); }

        // Replay Upload
        inline const char* Replay_Upload() const { return Get("Replay Upload"); }

        // Enable##framehistory_section label
        inline const char* Enable_framehistory_section_label() const { return Get("Enable##framehistory_section label"); }

        // Auto Reset label
        inline const char* Auto_Reset_label() const { return Get("Auto Reset label"); }

        // FrameHistory width label
        inline const char* FrameHistory_width_label() const { return Get("FrameHistory width label"); }

        // FrameHistory height label
        inline const char* FrameHistory_height_label() const { return Get("FrameHistory height label"); }

        // FrameHistory spacing label
        inline const char* FrameHistory_spacing_label() const { return Get("FrameHistory spacing label"); }

        // FrameHistory not enabled message
        inline const char* FrameHistory_not_enabled_message() const { return Get("FrameHistory not enabled message"); }

        // FrameHistory character load error
        inline const char* FrameHistory_character_load_error() const { return Get("FrameHistory character load error"); }

        // Language
        inline const char* Language() const { return Get("Language"); }

        // Language incomplete label
        inline const char* Language_incomplete_label() const { return Get("Language incomplete label"); }

        // Language selection help
        inline const char* Language_selection_help() const { return Get("Language selection help"); }

        // Active entities: %d
        inline const char* Active_entities_d() const { return Get("Active entities: %d"); }

        // Active entities with unk_status2 = 2: %d
        inline const char* Active_entities_with_unk_status2_2_d() const { return Get("Active entities with unk_status2 = 2: %d"); }

        // Only works during a running replay
        inline const char* Only_works_during_a_running_replay() const { return Get("Only works during a running replay"); }

        // Rewind
        inline const char* Rewind() const { return Get("Rewind"); }

        // Replay rewind help tooltip
        inline const char* Replay_rewind_help_tooltip() const { return Get("Replay rewind help tooltip"); }

        // Rewind Interval
        inline const char* Rewind_Interval() const { return Get("Rewind Interval"); }

        // Rewind interval help tooltip
        inline const char* Rewind_interval_help_tooltip() const { return Get("Rewind interval help tooltip"); }

        // 1s
        inline const char* _1s() const { return Get("1s"); }

        // 3s
        inline const char* _3s() const { return Get("3s"); }

        // 9s
        inline const char* _9s() const { return Get("9s"); }

        // Saved Checkpoints Adv. Info
        inline const char* Saved_Checkpoints_Adv_Info() const { return Get("Saved Checkpoints Adv. Info"); }

        // Rewind pos: +%d
        inline const char* Rewind_pos_d() const { return Get("Rewind pos: +%d"); }

        // snap_apparatus snapshot_count: %d
        inline const char* snap_apparatus_snapshot_count_d() const { return Get("snap_apparatus snapshot_count: %d"); }

        // %d: Framecount:%d
        inline const char* d_Framecount_d() const { return Get("%d: Framecount:%d"); }

        // Ranked_search_warning
        inline const char* Ranked_search_warning() const { return Get("Ranked_search_warning"); }

        // YOU ARE NOT IN A ROOM OR ONLINE MATCH!
        inline const char* YOU_ARE_NOT_IN_A_ROOM_OR_ONLINE_MATCH() const { return Get("YOU ARE NOT IN A ROOM OR ONLINE MATCH!"); }

        // Online type: %s
        inline const char* Online_type_s() const { return Get("Online type: %s"); }

        // Improvement Mod users in Room:
        inline const char* Improvement_Mod_users_in_Room() const { return Get("Improvement Mod users in Room:"); }

        // Improvement Mod users in match:
        inline const char* Improvement_Mod_users_in_match() const { return Get("Improvement Mod users in match:"); }

        // Click to open Steam profile
        inline const char* Click_to_open_Steam_profile() const { return Get("Click to open Steam profile"); }

        // Spectator
        inline const char* Spectator() const { return Get("Spectator"); }

        // Online room window title format
        inline const char* Online_room_window_title_format() const { return Get("Online room window title format"); }

        // Wine or Proton detected
        inline const char* Wine_or_Proton_detected() const { return Get("Wine or Proton detected"); }

        // Wine/Proton detected. Controller hooks were disabled to prevent startup crashes. Enable below or set ForceEnableControllerSettingHooks to 1 in settings.ini to override detection.
        inline const char* Wine_Proton_detected_Controller_hooks_were_disabled_to_prevent_startup_crashes_Enable_below_or_set_ForceEnableControllerSettingHooks_to_1_in_settings_ini_to_override_detection() const { return Get("Wine/Proton detected. Controller hooks were disabled to prevent startup crashes. Enable below or set ForceEnableControllerSettingHooks to 1 in settings.ini to override detection."); }

        // Enable anyway
        inline const char* Enable_anyway() const { return Get("Enable anyway"); }

        // Keep disabled
        inline const char* Keep_disabled() const { return Get("Keep disabled"); }

        // Controller hooks are disabled because EnableControllerHooks is set to 0.
        inline const char* Controller_hooks_are_disabled_because_EnableControllerHooks_is_set_to_0() const { return Get("Controller hooks are disabled because EnableControllerHooks is set to 0."); }

        // This might have been set manually or after detecting Wine/Proton.
        inline const char* This_might_have_been_set_manually_or_after_detecting_Wine_Proton() const { return Get("This might have been set manually or after detecting Wine/Proton."); }

        // To force enable these hooks, set ForceEnableControllerSettingHooks to 1 at your own risk.
        inline const char* To_force_enable_these_hooks_set_ForceEnableControllerSettingHooks_to_1_at_your_own_risk() const { return Get("To force enable these hooks, set ForceEnableControllerSettingHooks to 1 at your own risk."); }

        // Unlimited Playback (BETA)
        inline const char* Unlimited_Playback_BETA() const { return Get("Unlimited Playback (BETA)"); }

        // Popup is always available. Runtime actions only work in the right context.
        inline const char* Popup_is_always_available_Runtime_actions_only_work_in_the_right_context() const { return Get("Popup is always available. Runtime actions only work in the right context."); }

        // Loop current playback
        inline const char* Loop_current_playback() const { return Get("Loop current playback"); }

        // This will continuously loop the current recording slot
        inline const char* This_will_continuously_loop_the_current_recording_slot() const { return Get("This will continuously loop the current recording slot"); }

        // A native file dialog is already open.
        inline const char* A_native_file_dialog_is_already_open() const { return Get("A native file dialog is already open."); }

        // Mapped playback bind: %s
        inline const char* Mapped_playback_bind_s() const { return Get("Mapped playback bind: %s"); }

        // Profile Compatibility
        inline const char* Profile_Compatibility() const { return Get("Profile Compatibility"); }

        // Profile version mismatch.\n\nFile version: %s\nCode version: %s\n\n%s
        inline const char* Profile_version_mismatch_File_version_s_Code_version_s_s() const { return Get("Profile version mismatch.\n\nFile version: %s\nCode version: %s\n\n%s"); }

        // Load Anyway
        inline const char* Load_Anyway() const { return Get("Load Anyway"); }

        // Playback Compatibility
        inline const char* Playback_Compatibility() const { return Get("Playback Compatibility"); }

        // Playback version mismatch.\n\nFile version: %s\nCode version: %s\n\n%s
        inline const char* Playback_version_mismatch_File_version_s_Code_version_s_s() const { return Get("Playback version mismatch.\n\nFile version: %s\nCode version: %s\n\n%s"); }

        // Import Anyway
        inline const char* Import_Anyway() const { return Get("Import Anyway"); }

        // Add from CF Slot
        inline const char* Add_from_CF_Slot() const { return Get("Add from CF Slot"); }

        // Add from file
        inline const char* Add_from_file() const { return Get("Add from file"); }

        // Add from replay
        inline const char* Add_from_replay() const { return Get("Add from replay"); }

        // Capture a playback from one of the 4 CF slots
        inline const char* Capture_a_playback_from_one_of_the_4_CF_slots() const { return Get("Capture a playback from one of the 4 CF slots"); }

        // Import a playback file into the library
        inline const char* Import_a_playback_file_into_the_library() const { return Get("Import a playback file into the library"); }

        // Record a new playback entry from a replay
        inline const char* Record_a_new_playback_entry_from_a_replay() const { return Get("Record a new playback entry from a replay"); }

        // Library (%d)
        inline const char* Library_d() const { return Get("Library (%d)"); }

        // Send to CF Slot
        inline const char* Send_to_CF_Slot() const { return Get("Send to CF Slot"); }

        // Save to File
        inline const char* Save_to_File() const { return Get("Save to File"); }

        // Export playback entry file dialog open...
        inline const char* Export_playback_entry_file_dialog_open() const { return Get("Export playback entry file dialog open..."); }

        // Play
        inline const char* Play() const { return Get("Play"); }

        // Play (Disabled due to not being in lab)
        inline const char* Play_Disabled_due_to_not_being_in_lab() const { return Get("Play (Disabled due to not being in lab)"); }

        // Edit
        inline const char* Edit() const { return Get("Edit"); }

        // Delete
        inline const char* Delete() const { return Get("Delete"); }

        // Default
        inline const char* Default() const { return Get("Default"); }

        // Load a library profile
        inline const char* Load_a_library_profile() const { return Get("Load a library profile"); }

        // Save the current library as a profile
        inline const char* Save_the_current_library_as_a_profile() const { return Get("Save the current library as a profile"); }

        // Reset the current library
        inline const char* Reset_the_current_library() const { return Get("Reset the current library"); }

        // Load profile file dialog open...
        inline const char* Load_profile_file_dialog_open() const { return Get("Load profile file dialog open..."); }

        // Save profile file dialog open...
        inline const char* Save_profile_file_dialog_open() const { return Get("Save profile file dialog open..."); }

        // Add Playback Entry
        inline const char* Add_Playback_Entry() const { return Get("Add Playback Entry"); }

        // Add from replay is only available while a replay match is active in Replay Theater.
        inline const char* Add_from_replay_is_only_available_while_a_replay_match_is_active_in_Replay_Theater() const { return Get("Add from replay is only available while a replay match is active in Replay Theater."); }

        // Import playback file dialog open...
        inline const char* Import_playback_file_dialog_open() const { return Get("Import playback file dialog open..."); }

        // Add from Replay
        inline const char* Add_from_Replay_2() const { return Get("Add from Replay"); }

        // Capture from replay
        inline const char* Capture_from_replay() const { return Get("Capture from replay"); }

        // Recording %s inputs (start frame %d)
        inline const char* Recording_s_inputs_start_frame_d() const { return Get("Recording %s inputs (start frame %d)"); }

        // Name
        inline const char* Name() const { return Get("Name"); }

        // Stop and Save
        inline const char* Stop_and_Save() const { return Get("Stop and Save"); }

        // Record P1 Inputs
        inline const char* Record_P1_Inputs() const { return Get("Record P1 Inputs"); }

        // Record P2 Inputs
        inline const char* Record_P2_Inputs() const { return Get("Record P2 Inputs"); }

        // Replay capture only starts while a replay match is active.
        inline const char* Replay_capture_only_starts_while_a_replay_match_is_active() const { return Get("Replay capture only starts while a replay match is active."); }

        // Library Settings
        inline const char* Library_Settings() const { return Get("Library Settings"); }

        // Random
        inline const char* Random() const { return Get("Random"); }

        // Sequential
        inline const char* Sequential() const { return Get("Sequential"); }

        // Non-repeating Random
        inline const char* Non_repeating_Random() const { return Get("Non-repeating Random"); }

        // Playback Mode
        inline const char* Playback_Mode() const { return Get("Playback Mode"); }

        // How the library chooses the next enabled entry when playback is triggered.
        inline const char* How_the_library_chooses_the_next_enabled_entry_when_playback_is_triggered() const { return Get("How the library chooses the next enabled entry when playback is triggered."); }

        // Playback mode: %s
        inline const char* Playback_mode_s() const { return Get("Playback mode: %s"); }

        // Auto-mirror on side swap
        inline const char* Auto_mirror_on_side_swap() const { return Get("Auto-mirror on side swap"); }

        // Mirrors directional inputs when the recorded side and current side differ.
        inline const char* Mirrors_directional_inputs_when_the_recorded_side_and_current_side_differ() const { return Get("Mirrors directional inputs when the recorded side and current side differ."); }

        // Wakeup
        inline const char* Wakeup() const { return Get("Wakeup"); }

        // On Block
        inline const char* On_Block() const { return Get("On Block"); }

        // On Hit
        inline const char* On_Hit() const { return Get("On Hit"); }

        // Throw Tech
        inline const char* Throw_Tech() const { return Get("Throw Tech"); }

        // Key Press
        inline const char* Key_Press() const { return Get("Key Press"); }

        // Unknown
        inline const char* Unknown() const { return Get("Unknown"); }

        // Playback Trigger Type
        inline const char* Playback_Trigger_Type() const { return Get("Playback Trigger Type"); }

        // Selects the single trigger type that can fire library playback.
        inline const char* Selects_the_single_trigger_type_that_can_fire_library_playback() const { return Get("Selects the single trigger type that can fire library playback."); }

        // Playback trigger: %s
        inline const char* Playback_trigger_s() const { return Get("Playback trigger: %s"); }

        // %s Config
        inline const char* s_Config() const { return Get("%s Config"); }

        // Cooldown Frames
        inline const char* Cooldown_Frames() const { return Get("Cooldown Frames"); }

        // Blocks the same trigger from firing again for this many frames after it activates.
        inline const char* Blocks_the_same_trigger_from_firing_again_for_this_many_frames_after_it_activates() const { return Get("Blocks the same trigger from firing again for this many frames after it activates."); }

        // Maps the button or key used by the Key Press trigger.
        inline const char* Maps_the_button_or_key_used_by_the_Key_Press_trigger() const { return Get("Maps the button or key used by the Key Press trigger."); }

        // Map Playback Bind
        inline const char* Map_Playback_Bind() const { return Get("Map Playback Bind"); }

        // Fix Triggers
        inline const char* Fix_Triggers() const { return Get("Fix Triggers"); }

        // Use this after Training reset if triggers temporarily stop firing. It clears trigger cooldown and edge state.
        inline const char* Use_this_after_Training_reset_if_triggers_temporarily_stop_firing_It_clears_trigger_cooldown_and_edge_state() const { return Get("Use this after Training reset if triggers temporarily stop firing. It clears trigger cooldown and edge state."); }

        // Activity
        inline const char* Activity() const { return Get("Activity"); }

        // Reset Library?
        inline const char* Reset_Library() const { return Get("Reset Library?"); }

        // Reset the current library and clear all loaded entries?
        inline const char* Reset_the_current_library_and_clear_all_loaded_entries() const { return Get("Reset the current library and clear all loaded entries?"); }

        // Reset
        inline const char* Reset_2() const { return Get("Reset"); }

        // Delete Entry?
        inline const char* Delete_Entry() const { return Get("Delete Entry?"); }

        // Delete this playback entry from the library?
        inline const char* Delete_this_playback_entry_from_the_library() const { return Get("Delete this playback entry from the library?"); }

        // Capture Slot
        inline const char* Capture_Slot() const { return Get("Capture Slot"); }

        // Edit Library Entry
        inline const char* Edit_Library_Entry() const { return Get("Edit Library Entry"); }

        // Weight
        inline const char* Weight() const { return Get("Weight"); }

        // Edit Playback
        inline const char* Edit_Playback() const { return Get("Edit Playback"); }

        // Entry updated.
        inline const char* Entry_updated() const { return Get("Entry updated."); }

        // Edit Entry Playback
        inline const char* Edit_Entry_Playback() const { return Get("Edit Entry Playback"); }

        // Playback editor is unavailable.
        inline const char* Playback_editor_is_unavailable() const { return Get("Playback editor is unavailable."); }

        // Entry no longer exists.
        inline const char* Entry_no_longer_exists() const { return Get("Entry no longer exists."); }

        // CF Slot
        inline const char* CF_Slot() const { return Get("CF Slot"); }

        // Send
        inline const char* Send() const { return Get("Send"); }

        // Load unlimited playback profile
        inline const char* Load_unlimited_playback_profile() const { return Get("Load unlimited playback profile"); }

        // Save unlimited playback profile
        inline const char* Save_unlimited_playback_profile() const { return Get("Save unlimited playback profile"); }

        // Import unlimited playback entry
        inline const char* Import_unlimited_playback_entry() const { return Get("Import unlimited playback entry"); }

        // Export unlimited playback entry
        inline const char* Export_unlimited_playback_entry() const { return Get("Export unlimited playback entry"); }

        // Pad A
        inline const char* Pad_A() const { return Get("Pad A"); }

        // Pad B
        inline const char* Pad_B() const { return Get("Pad B"); }

        // Pad X
        inline const char* Pad_X() const { return Get("Pad X"); }

        // Pad Y
        inline const char* Pad_Y() const { return Get("Pad Y"); }

        // Pad LB
        inline const char* Pad_LB() const { return Get("Pad LB"); }

        // Pad RB
        inline const char* Pad_RB() const { return Get("Pad RB"); }

        // Pad Back
        inline const char* Pad_Back() const { return Get("Pad Back"); }

        // Pad Start
        inline const char* Pad_Start() const { return Get("Pad Start"); }

        // Pad LS
        inline const char* Pad_LS() const { return Get("Pad LS"); }

        // Pad RS
        inline const char* Pad_RS() const { return Get("Pad RS"); }

        // Pad Up
        inline const char* Pad_Up() const { return Get("Pad Up"); }

        // Pad Down
        inline const char* Pad_Down() const { return Get("Pad Down"); }

        // Pad Left
        inline const char* Pad_Left() const { return Get("Pad Left"); }

        // Pad Right
        inline const char* Pad_Right() const { return Get("Pad Right"); }

        // VK_%d
        inline const char* VK_d() const { return Get("VK_%d"); }

        // Invalid playback destination.
        inline const char* Invalid_playback_destination() const { return Get("Invalid playback destination."); }

        // Playback payload was too small.
        inline const char* Playback_payload_was_too_small() const { return Get("Playback payload was too small."); }

        // Playback rejected: file v%s, code v%s.
        inline const char* Playback_rejected_file_v_s_code_v_s() const { return Get("Playback rejected: file v%s, code v%s."); }

        // Playback file header is missing.
        inline const char* Playback_file_header_is_missing() const { return Get("Playback file header is missing."); }

        // Trigger runtime state reset.
        inline const char* Trigger_runtime_state_reset() const { return Get("Trigger runtime state reset."); }

        // Trigger runtime resynced after training reset.
        inline const char* Trigger_runtime_resynced_after_training_reset() const { return Get("Trigger runtime resynced after training reset."); }

        // Could not read playback file.
        inline const char* Could_not_read_playback_file() const { return Get("Could not read playback file."); }

        // File not found.
        inline const char* File_not_found() const { return Get("File not found."); }

        // Invalid playback file.
        inline const char* Invalid_playback_file() const { return Get("Invalid playback file."); }

        // Playback imported.
        inline const char* Playback_imported() const { return Get("Playback imported."); }

        // Slot must be between 1 and 4.
        inline const char* Slot_must_be_between_1_and_4() const { return Get("Slot must be between 1 and 4."); }

        // Captured slot to library.
        inline const char* Captured_slot_to_library() const { return Get("Captured slot to library."); }

        // Start replay recording only while a replay match is active.
        inline const char* Start_replay_recording_only_while_a_replay_match_is_active() const { return Get("Start replay recording only while a replay match is active."); }

        // Replay recording started: %s.
        inline const char* Replay_recording_started_s() const { return Get("Replay recording started: %s."); }

        // No replay recording in progress.
        inline const char* No_replay_recording_in_progress() const { return Get("No replay recording in progress."); }

        // Replay recording cancelled (left replay match).
        inline const char* Replay_recording_cancelled_left_replay_match() const { return Get("Replay recording cancelled (left replay match)."); }

        // Replay recording cancelled (too short).
        inline const char* Replay_recording_cancelled_too_short() const { return Get("Replay recording cancelled (too short)."); }

        // Replay recording cancelled (failed reading replay frames).
        inline const char* Replay_recording_cancelled_failed_reading_replay_frames() const { return Get("Replay recording cancelled (failed reading replay frames)."); }

        // Replay recording saved to library.
        inline const char* Replay_recording_saved_to_library() const { return Get("Replay recording saved to library."); }

        // Entry removed.
        inline const char* Entry_removed() const { return Get("Entry removed."); }

        // Entry renamed.
        inline const char* Entry_renamed() const { return Get("Entry renamed."); }

        // Sending to a CF slot works only during a training match.
        inline const char* Sending_to_a_CF_slot_works_only_during_a_training_match() const { return Get("Sending to a CF slot works only during a training match."); }

        // Failed loading entry.
        inline const char* Failed_loading_entry() const { return Get("Failed loading entry."); }

        // Entry loaded into slot.
        inline const char* Entry_loaded_into_slot() const { return Get("Entry loaded into slot."); }

        // Entry overwritten from slot.
        inline const char* Entry_overwritten_from_slot() const { return Get("Entry overwritten from slot."); }

        // Entry saved.
        inline const char* Entry_saved() const { return Get("Entry saved."); }

        // Failed saving entry to file.
        inline const char* Failed_saving_entry_to_file() const { return Get("Failed saving entry to file."); }

        // Entry saved to file.
        inline const char* Entry_saved_to_file() const { return Get("Entry saved to file."); }

        // Play now works only during a training match.
        inline const char* Play_now_works_only_during_a_training_match() const { return Get("Play now works only during a training match."); }

        // Played: %s%s
        inline const char* Played_s_s() const { return Get("Played: %s%s"); }

        // (mirrored)
        inline const char* mirrored() const { return Get("(mirrored)"); }

        // Unlimited playback config cleared.
        inline const char* Unlimited_playback_config_cleared() const { return Get("Unlimited playback config cleared."); }

        // Failed to save profile.
        inline const char* Failed_to_save_profile() const { return Get("Failed to save profile."); }

        // Profile save failed: entry data missing for '%s'.
        inline const char* Profile_save_failed_entry_data_missing_for_s() const { return Get("Profile save failed: entry data missing for '%s'."); }

        // Profile saved.
        inline const char* Profile_saved() const { return Get("Profile saved."); }

        // Could not read profile file.
        inline const char* Could_not_read_profile_file() const { return Get("Could not read profile file."); }

        // Failed to open profile.
        inline const char* Failed_to_open_profile() const { return Get("Failed to open profile."); }

        // Playback rejected (newer format): file v%s, code v%s.
        inline const char* Playback_rejected_newer_format_file_v_s_code_v_s() const { return Get("Playback rejected (newer format): file v%s, code v%s."); }

        // Profile compatibility rejected (file v%s, code v%s).
        inline const char* Profile_compatibility_rejected_file_v_s_code_v_s() const { return Get("Profile compatibility rejected (file v%s, code v%s)."); }

        // Profile version mismatch requires confirmation (file v%s, code v%s).
        inline const char* Profile_version_mismatch_requires_confirmation_file_v_s_code_v_s() const { return Get("Profile version mismatch requires confirmation (file v%s, code v%s)."); }

        // Profile load failed: embedded playback missing for '%s'.
        inline const char* Profile_load_failed_embedded_playback_missing_for_s() const { return Get("Profile load failed: embedded playback missing for '%s'."); }

        // Profile load failed for '%s': %s
        inline const char* Profile_load_failed_for_s_s() const { return Get("Profile load failed for '%s': %s"); }

        // Profile load failed for '%s'.
        inline const char* Profile_load_failed_for_s() const { return Get("Profile load failed for '%s'."); }

        // Profile loaded. Trigger runtime synced.
        inline const char* Profile_loaded_Trigger_runtime_synced() const { return Get("Profile loaded. Trigger runtime synced."); }

        // Trigger detected: %s
        inline const char* Trigger_detected_s() const { return Get("Trigger detected: %s"); }

        // No eligible playback in current trigger selection.
        inline const char* No_eligible_playback_in_current_trigger_selection() const { return Get("No eligible playback in current trigger selection."); }

        // Selected playback cache missing.
        inline const char* Selected_playback_cache_missing() const { return Get("Selected playback cache missing."); }

        // Triggered [%s]: %s%s
        inline const char* Triggered_s_s_s() const { return Get("Triggered [%s]: %s%s"); }

        // Slot %d
        inline const char* Slot_d() const { return Get("Slot %d"); }

        // Replay %s
        inline const char* Replay_s() const { return Get("Replay %s"); }
};


